defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  reproduce:
    strategy:
      matrix:
        script: ['control.py', 'reproduce.py']
    runs-on: 'ubuntu-latest'
    env:
      PYTHON_VERSION: '3.10'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          cache-downloads: true
          post-cleanup: 'all'
          create-args: >-
            python=3.10
      - name: Check installation
        run: |
          python -c "import numpy; print(numpy.__version__)"
          python -c "import mlir; print(mlir.__package__)"
      - name: Run scripts
        run: |
          DEBUG=1 python ${{ matrix.script }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
